[package]
name = "gateway-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
gateway = { path = ".." }

[[bin]]
name = "fuzz_request_parser"
path = "fuzz_targets/fuzz_request_parser.rs"
test = false
doc = false
bench = false

[[bin]]
name = "fuzz_token_verifier"
path = "fuzz_targets/fuzz_token_verifier.rs"
test = false
doc = false
bench = false
