[package]
name = "aegis-eval"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Justin B. Thompson (Aefinity AI)"]
repository = "https://github.com/Aefinity-AI/alice-aegis"

[dependencies]
aegis-core = { path = "../aegis-core" }

[features]
int8_act = ["aegis-core/int8_act"]
parallel = ["aegis-core/parallel"]
