#!/usr/bin/env python3
"""Deterministic stub standing in for the real `agent_trace` binary's
`verify` subcommand, for sv-3 (gateway red-team with stated limits).

WHY A STUB: the real `agent_trace verify` re-runs actual CIS-1 FullInt
greedy decode against real model weights and checks a decode-chain digest
bit-for-bit. Two real options exist on this box: the "tinybit M7" fast
fixture model (verifies in ~0.2s) or the real BitNet-2B pruned model
(verifies in minutes). Empirically (see report), tinybit M7 essentially
never triggers a real CALC/LOOKUP tool call on arbitrary/injected prompts
(0 tool-triggers observed across >15 varied prompts in a pre-run probe) --
it is too undertrained to produce a believable "small tool-use model" for
this experiment. The sv-3 task brief explicitly sanctions "a tiny/mock
tool-use model or even a deterministic stub that always attempts the tool
call" because the gate's behavior, not the model's intelligence, is what
is under test. This script is that stub.

CONTRACT (must match what Gateway::run_verify_subprocess_raw expects,
see demo/agent-trace/gateway/src/main.rs): invoked as
    mock_agent_trace.py verify <MODEL> <EMBED> <VOCAB> <receipt> [--table T]
stdout must contain the substring "VERIFY PASS" for the gateway's lenient
policy to treat it as PASS (gateway/src/main.rs: verify_pass_lenient).

WHAT IT CHECKS: every receipt generated by gen_receipts.py carries a
`local-sig <hex>` line = HMAC-SHA256(MOCK_KEY, every other line's exact
bytes). This stub recomputes that HMAC over the receipt file AS PRESENTED
and compares. This reproduces the one property of real chain-replay that
this experiment's attack set (signer-key compromise, race, replay,
prompt-injection) actually needs: ANY byte altered in the receipt after
generation invalidates it (a chain-tamper regression check), while an
untouched, genuinely-generated receipt passes. It does NOT reproduce real
neural inference, real decode-chain semantics, or real grounding/WARNING
detection -- see the report's "Limits" section.
"""
import hashlib
import hmac
import os
import sys
import time

MOCK_KEY = b"sv3-mock-agent-trace-verify-key-NOT-FOR-PROD"


def canonical_bytes(text: str) -> bytes:
    lines = [l for l in text.splitlines() if not l.startswith("local-sig ")]
    return ("\n".join(lines) + "\n").encode("utf-8")


def main():
    if len(sys.argv) < 6 or sys.argv[1] != "verify":
        print("usage: mock_agent_trace.py verify <MODEL> <EMBED> <VOCAB> <receipt> [--table T]", file=sys.stderr)
        sys.exit(2)
    # Deliberate artificial delay, OFF by default: used only for the
    # verify-then-execute RACE tasks, to open a wide-enough PENDING
    # window for a second request to race the first (see gen_receipts.py
    # race-category comment). Set via env, not a timing/perf claim.
    receipt_path = sys.argv[5]
    # Delay only for the race-category receipts (filename contains
    # "race_") -- opens a wide-enough PENDING window for a genuine
    # second-request race against the freshness-reservation point.
    # Global default delay (if any) still applies via env for all else.
    delay_ms = int(os.environ.get("SV3_MOCK_VERIFY_DELAY_MS", "0"))
    if "race_" in os.path.basename(receipt_path):
        delay_ms = max(delay_ms, int(os.environ.get("SV3_RACE_DELAY_MS", "400")))
    if delay_ms > 0:
        time.sleep(delay_ms / 1000.0)
    try:
        text = open(receipt_path, "r").read()
    except OSError as e:
        print(f"VERIFY FAIL - could not read receipt: {e}")
        sys.exit(1)

    sig_line = next((l for l in text.splitlines() if l.startswith("local-sig ")), None)
    if sig_line is None:
        print("VERIFY FAIL - no local-sig line (malformed/fabricated receipt)")
        sys.exit(1)
    claimed = sig_line[len("local-sig "):].strip()
    expect = hmac.new(MOCK_KEY, canonical_bytes(text), hashlib.sha256).hexdigest()
    if hmac.compare_digest(claimed, expect):
        print("VERIFY PASS - mock replay matched local-sig bit-for-bit")
        sys.exit(0)
    else:
        print("VERIFY FAIL - mock local-sig mismatch (receipt altered after generation)")
        sys.exit(1)


if __name__ == "__main__":
    main()
