//! CIS-1 v0.3 — the integer attention & activation organs: ROPE-I,
//! SOFTMAX-I, ACT-I.
//!
//! Spec: `docs/CIS-1_SPEC_DRAFT_v0.1.md`, "v0.3 integer-attention notes".
//! These ops close E2's declared hybrid gap: with them, `cis_infer`'s
//! FULL-INTEGER mode runs the entire forward pass in exact integer /
//! fixed-point arithmetic — no float value ever enters the computation, so
//! cross-kernel-path and cross-ISA bit-identity holds BY CONSTRUCTION
//! (every loop below is scalar integer Rust; there is no SIMD dispatch to
//! diverge from).
//!
//! Everything here is `core`-only integer arithmetic — no floats, no
//! `libm`, no `unsafe`. All rounding goes through `cis::rne_div`
//! (round-half-even), the module's single rounding primitive. Every
//! normative constant is either a pinned integer literal (π, log2 e — from
//! published decimal expansions) or the output of a parameter-free integer
//! procedure (floor `isqrt` chains, squaring-based log2, Taylor sums with
//! exact factorial divisors). Golden tests pin the constants against the
//! INDEPENDENT Python big-int generator (`scripts/cis_e2_golden_gen.py`).

use alloc::vec::Vec;

use crate::cis::rne_div;

// ---------------------------------------------------------------------------
// Normative constants (pinned integer literals; derivation cited in the
// spec notes: round-half-even of published 50-digit decimal expansions).
// ---------------------------------------------------------------------------

/// 2π in Q2.62: `rne(2π · 2^62)`.
pub const TWO_PI_Q62: u128 = 28976077832308491370;
/// π in Q2.62: `rne(π · 2^62)`.
pub const PI_Q62: u128 = 14488038916154245685;
/// π/2 in Q2.62: `rne(π/2 · 2^62)`.
pub const PI_2_Q62: u128 = 7244019458077122842;
/// log2(e) in Q32.32: `rne(2^32 / ln 2)`.
pub const LOG2E_Q32: i64 = 6196328019;

// ---------------------------------------------------------------------------
// exp2 machinery: the floor-isqrt chain and the normative 1025-entry LUT.
// ---------------------------------------------------------------------------

/// Chain constants `C[k] = 2^(−2^(−k))` in Q0.62, k = 1..=32, generated by
/// the parameter-free normative procedure: `C[0] = 2^61` (= 1/2), then
/// `C[k] = isqrt(C[k−1] · 2^62)` (floor integer square root — exact, unique,
/// nothing to freeze). `C[0]` is the seed, not itself used as a factor.
pub fn exp2_chain() -> [u64; 33] {
    let mut c = [0u64; 33];
    c[0] = 1 << 61;
    for k in 1..=32 {
        c[k] = (((c[k - 1] as u128) << 62).isqrt()) as u64;
    }
    c
}

/// `2^(−f)` for `f` in Q0.32 ∈ [0, 2^32), result Q0.62 ∈ (2^61, 2^62].
/// Product over the set bits of `f` of the chain constants, RNE-requantized
/// to Q0.62 after each multiply (bit k of the fraction, MSB first, selects
/// `C[k]`). Used at table-generation time only (LUT + RoPE inv-freq), where
/// consecutive arguments are far apart, so its last-ulp non-monotonicity
/// can never surface in a table.
pub fn exp2_neg_frac(f_q32: u64, chain: &[u64; 33]) -> u128 {
    debug_assert!(f_q32 < 1 << 32);
    let mut acc: u128 = 1 << 62;
    for (k, &c) in chain.iter().enumerate().take(33).skip(1) {
        if (f_q32 >> (32 - k)) & 1 == 1 {
            acc = rne_div((acc * c as u128) as i128, 1 << 62) as u128;
        }
    }
    acc
}

/// The normative exp LUT: `E[i] = rne(2^(−i/1024) · 2^31)` for i = 0..1024
/// via the chain, plus the exact endpoint `E[1024] = 2^30`. Entries are
/// strictly decreasing (the function drops ≈ 1.45M Q0.31 ulps per entry;
/// chain + rounding error is a few ulps), which makes interpolated lookup
/// provably monotone.
pub struct ExpLut {
    e: Vec<i64>,
}

impl ExpLut {
    pub fn new() -> ExpLut {
        let chain = exp2_chain();
        let mut e = Vec::with_capacity(1025);
        for i in 0..1024u64 {
            e.push(rne_div(exp2_neg_frac(i << 22, &chain) as i128, 1 << 31) as i64);
        }
        e.push(1 << 30);
        ExpLut { e }
    }

    /// Entry access for goldens/digests.
    pub fn entry(&self, i: usize) -> i64 {
        self.e[i]
    }

    /// `2^(−f)` for `f` in Q0.32 ∈ [0, 2^32), Q0.31 ∈ [2^30, 2^31], by
    /// linear interpolation between the two straddling entries (top 10 bits
    /// index, low 22 bits interpolate). Monotone non-increasing in `f`:
    /// each segment is linear with a non-positive slope and segments join
    /// continuously at the entries.
    pub fn exp2_neg(&self, f_q32: u64) -> i64 {
        debug_assert!(f_q32 < 1 << 32);
        let i = (f_q32 >> 22) as usize;
        let r = (f_q32 & ((1 << 22) - 1)) as i128;
        let a = self.e[i];
        let b = self.e[i + 1];
        a - rne_div((a - b) as i128 * r, 1 << 22) as i64
    }
}

impl Default for ExpLut {
    fn default() -> Self {
        ExpLut::new()
    }
}

/// `e^(−z)` for `z ≥ 0` in Q32.32 (as u128 so callers with wide integer
/// grids never overflow), result Q0.31 ∈ [0, 2^31]. Route through base 2:
/// `y = z · log2(e)` (exact product, Q.64), split into integer part `n`
/// and RNE-rounded Q0.32 fraction `f`, then `E(f) / 2^n`. `n ≥ 31` (i.e.
/// `z > ~21.49`) underflows to exactly 0.
///
/// Monotone non-increasing in `z`: `y` is an exact monotone map, the
/// `(n, f)` split with the carry fold is lexicographically monotone with
/// continuous boundaries (`f → 2^32` folds to `(n+1, 0)`, and
/// `E(2^32) = E(0)/2` by the endpoint entry), `exp2_neg` is monotone, and
/// division by `2^n` preserves it. The property test asserts this.
pub fn exp_neg_q31(z_q32: u128, lut: &ExpLut) -> i64 {
    let y = z_q32 * LOG2E_Q32 as u128; // Q.64; callers keep z < 2^68
    let mut n = (y >> 64) as u32;
    if n >= 31 {
        return 0;
    }
    let mut f = rne_div((y & ((1u128 << 64) - 1)) as i128, 1 << 32) as u64;
    if f == 1 << 32 {
        n += 1;
        f = 0;
        if n >= 31 {
            return 0;
        }
    }
    rne_div(lut.exp2_neg(f) as i128, 1 << n) as i64
}

// ---------------------------------------------------------------------------
// SOFTMAX-I
// ---------------------------------------------------------------------------

/// SOFTMAX-I (spec v0.3): integer softmax over attention scores on the
/// Q40.24 score grid, producing Q0.15 probabilities.
///
/// Steps, all exact-integer:
///   1. `m = max(scores)` — exact i64 compare;
///   2. `e_t = exp_neg_q31((m − s_t) << 8)` (Q.24 → Q.32 arg is an exact
///      shift; the max element gets e = 2^31 exactly);
///   3. `S = Σ e_t` in i64 (≤ T · 2^31, exact for T ≤ 2^32);
///   4. `p_t = rne(e_t · 2^15 / S)` — RNE division, Q0.15.
///
/// `scores` is overwritten with the intermediate `e_t` values (the caller's
/// score buffer doubles as exp scratch — the engine is zero-allocation).
///
/// Declared bounds (property-tested):
///   - sum-to-one: `|Σ p_t − 2^15| ≤ ⌈T/2⌉` (each p carries ≤ 1/2 ulp of
///     RNE error and the e_t normalize exactly against their own sum);
///   - monotone: `s_i ≥ s_j ⇒ p_i ≥ p_j` (exact, from exp_neg_q31's
///     monotonicity and the shared divisor);
///   - underflow: a score more than ~21.49 real units below the max (Q.24:
///     z ≥ 31·2^32 in the exp argument) gets p = 0 exactly. The discarded
///     tail mass is < T·e^(−21.49) < 2.4e−7 for T ≤ 512 — below one Q0.15
///     ulp, i.e. below the output's own resolution.
pub fn softmax_i(scores: &mut [i64], probs: &mut [i32], lut: &ExpLut) {
    let n = scores.len();
    assert!(n > 0, "softmax_i: empty scores");
    assert!(
        n <= 1 << 20,
        "softmax_i: sequence too long for exact i64 sum"
    );
    assert!(probs.len() >= n, "softmax_i: probs buffer too short");
    let m = *scores.iter().max().unwrap();
    for s in scores.iter_mut() {
        let z = (m - *s) as u128; // ≥ 0, exact
        *s = exp_neg_q31(z << 8, lut); // Q.24 → Q.32 argument, exact shift
    }
    let mut sum: i64 = 0;
    for &e in scores.iter() {
        sum += e;
    }
    debug_assert!(
        sum >= 1 << 31,
        "softmax_i: max element must contribute 2^31"
    );
    for (p, &e) in probs.iter_mut().zip(scores.iter()) {
        *p = rne_div((e as i128) << 15, sum as i128) as i32;
    }
}

// ---------------------------------------------------------------------------
// ROPE-I: normative integer sin/cos tables + rotation.
// ---------------------------------------------------------------------------

/// `log2(value)` of a finite f32 with value ≥ 2, in Q32.32, by the
/// normative shift-and-square procedure: decompose the bit pattern into
/// `M · 2^E` with `M ∈ [1, 2)` held in Q2.62, then extract 32 fraction bits
/// by repeated squaring (RNE requant to Q2.62 each step; a renormalizing
/// halving — also RNE — emits a 1 bit). Integer-only, parameter-free.
pub fn log2_q32_f32(bits: u32) -> u64 {
    let exp = ((bits >> 23) & 0xFF) as i32;
    let man = bits & 0x7F_FFFF;
    assert!(
        bits >> 31 == 0 && exp != 0xFF && exp >= 128,
        "log2_q32_f32: RoPE base must be finite and >= 2"
    );
    let e = (exp - 127) as u64;
    let mut m: u128 = ((man as u128) | (1 << 23)) << 39; // Q2.62 ∈ [2^62, 2^63)
    let mut frac: u64 = 0;
    for _ in 0..32 {
        m = rne_div((m * m) as i128, 1 << 62) as u128;
        frac <<= 1;
        if m >= 1 << 63 {
            m = rne_div(m as i128, 2) as u128;
            frac |= 1;
        }
    }
    (e << 32) | frac
}

/// `(sin x, cos x)` for `x ∈ [0, 2π)` in Q2.62, results signed Q0.62.
///
/// Normative procedure: quadrant reduction against the pinned π constants
/// (`sin(x+π) = −sin x`; `sin(π−x) = sin x, cos(π−x) = −cos x`; a reduction
/// that lands 1 ulp below 0 saturates to 0), then 9-term Taylor sums on
/// [0, π/2] in Q0.62 with RNE requant after each multiply and exact integer
/// factorial divisors — no free coefficients exist. Truncation < 2^−40,
/// accumulated rounding ≲ 40 ulps of 2^−62: error is far below the Q1.30
/// table quantization that consumes these values.
pub fn sincos_q62(x: u128) -> (i64, i64) {
    debug_assert!(
        x < TWO_PI_Q62,
        "sincos_q62: argument must be reduced mod 2π"
    );
    let mut x = x;
    let mut sign_s: i128 = 1;
    let mut sign_c: i128 = 1;
    if x >= PI_Q62 {
        x -= PI_Q62;
        sign_s = -1;
        sign_c = -1;
    }
    if x >= PI_2_Q62 {
        x = PI_Q62.saturating_sub(x).min(PI_2_Q62);
        sign_c = -sign_c;
    }
    let xi = x as i128; // ≤ π/2 · 2^62 < 2^63
    let x2 = rne_div(xi * xi, 1 << 62); // Q0.62, ≤ ~2.47 · 2^62

    let mut t = xi;
    let mut s = xi;
    for k in 1..9i128 {
        t = rne_div(t * x2, 1 << 62);
        t = rne_div(t, (2 * k) * (2 * k + 1));
        s += if k & 1 == 1 { -t } else { t };
    }

    let mut t: i128 = 1 << 62;
    let mut c: i128 = 1 << 62;
    for k in 1..9i128 {
        t = rne_div(t * x2, 1 << 62);
        t = rne_div(t, (2 * k - 1) * (2 * k));
        c += if k & 1 == 1 { -t } else { t };
    }

    ((s * sign_s) as i64, (c * sign_c) as i64)
}

/// ROPE-I tables: Q1.30 i32 sin/cos per (position, frequency), generated at
/// load by the normative integer-only procedure — the same bits on every
/// platform, so the TABLE is reproducible from (max_seq, head_dim,
/// base_bits) alone and its FNV digest is golden-tested.
///
/// Generation rule per (pos, d), d < head_dim/2:
///   1. `L = log2_q32_f32(base_bits)`;
///   2. `a_d = rne(2d · L / head_dim)` (Q.32) — the exponent of the
///      inverse frequency `base^(−2d/head_dim) = 2^(−a_d)`;
///   3. `inv_freq_d = rne(exp2_neg_frac(frac(a_d)) / 2^int(a_d))` (Q0.62,
///      via the chain — absolute error ≤ ~2^−62, so even pos·error stays
///      below 2^−52 rad);
///   4. `θ = pos · inv_freq_d` (exact), reduced `θ mod TWO_PI_Q62`;
///   5. `(sin, cos) = sincos_q62(θ)`, RNE-requantized to Q1.30 and clamped
///      to ±2^30 (cos 0 = +2^30 exactly).
pub struct RopeTableI {
    pub cos: Vec<i32>,
    pub sin: Vec<i32>,
    pub max_seq: usize,
    pub half_dim: usize,
}

impl RopeTableI {
    pub fn new(max_seq: usize, head_dim: usize, base_bits: u32) -> RopeTableI {
        assert!(
            head_dim >= 2 && head_dim.is_multiple_of(2),
            "RoPE needs an even head_dim"
        );
        let half = head_dim / 2;
        let chain = exp2_chain();
        let l = log2_q32_f32(base_bits);
        let mut inv_freq: Vec<u128> = Vec::with_capacity(half); // Q0.62
        for d in 0..half {
            let a = rne_div(2 * d as i128 * l as i128, head_dim as i128) as u64;
            let n = a >> 32;
            let f = a & 0xFFFF_FFFF;
            assert!(n < 62, "RoPE-I: inverse frequency underflows Q0.62");
            inv_freq.push(rne_div(exp2_neg_frac(f, &chain) as i128, 1i128 << n) as u128);
        }
        let mut cos = Vec::with_capacity(max_seq * half);
        let mut sin = Vec::with_capacity(max_seq * half);
        for pos in 0..max_seq {
            for &ivf in &inv_freq {
                let theta = pos as u128 * ivf; // ≤ max_seq · 2^62, exact
                let r = theta % TWO_PI_Q62;
                let (s, c) = sincos_q62(r);
                cos.push(rne_div(c as i128, 1 << 32).clamp(-(1 << 30), 1 << 30) as i32);
                sin.push(rne_div(s as i128, 1 << 32).clamp(-(1 << 30), 1 << 30) as i32);
            }
        }
        RopeTableI {
            cos,
            sin,
            max_seq,
            half_dim: half,
        }
    }
}

/// ROPE-I rotation over fixed-point q/k (any common Q.f grid; the engine
/// uses Q.16). Same pairing as the production `attention::apply_rope`
/// (d, d + half_dim), arithmetic `rne((q0·cos − q1·sin) / 2^30)` in i64/i128
/// intermediates. Requires |q|, |k| < 2^30 so the rotated values (≤ √2·|q|
/// + 1 ulp) still fit i32; the engine's rescale asserts a stricter 2^29.
pub fn rope_apply_i(
    q: &mut [i32],
    k: &mut [i32],
    seq_pos: usize,
    num_heads: usize,
    num_kv_heads: usize,
    head_dim: usize,
    tab: &RopeTableI,
) {
    if seq_pos >= tab.max_seq {
        return;
    }
    let half = head_dim / 2;
    debug_assert_eq!(half, tab.half_dim);
    let off = seq_pos * half;
    let rotate = |v: &mut [i32]| {
        for d in 0..half {
            let c = tab.cos[off + d] as i128;
            let s = tab.sin[off + d] as i128;
            let v0 = v[d] as i128;
            let v1 = v[d + half] as i128;
            v[d] = rne_div(v0 * c - v1 * s, 1 << 30) as i32;
            v[d + half] = rne_div(v0 * s + v1 * c, 1 << 30) as i32;
        }
    };
    for h in 0..num_heads {
        rotate(&mut q[h * head_dim..(h + 1) * head_dim]);
    }
    for h in 0..num_kv_heads {
        rotate(&mut k[h * head_dim..(h + 1) * head_dim]);
    }
}

/// `1/sqrt(n)` in Q0.30 by the parameter-free rule
/// `rne(2^60 / isqrt(n · 2^60))` — exact for power-of-four n (head_dim 64
/// gives exactly 2^27 = 0.125). Used to scale attention scores.
pub fn inv_sqrt_q30(n: u64) -> i64 {
    assert!(n > 0, "inv_sqrt_q30: n must be positive");
    let s = ((n as u128) << 60).isqrt(); // floor(sqrt(n) · 2^30)
    rne_div(1i128 << 60, s as i128) as i64
}

// ---------------------------------------------------------------------------
// ACT-I: integer MLP elementwise stage.
// ---------------------------------------------------------------------------

/// Integer relu²·up on the Q.20 grid: `rne(max(0, g)² / 2^20) · u`,
/// RNE-requantized back to Q.20. Exact up to the two declared RNE requants;
/// intermediates in i128 (callers assert |g|, |u| < 2^40, so the final
/// product magnitude is < 2^80 and the i64 assert below is the loud guard).
pub fn relu2_q20(g: i64, u: i64) -> i64 {
    if g <= 0 {
        return 0;
    }
    let a = rne_div(g as i128 * g as i128, 1 << 20); // Q.20
    let r = rne_div(a * u as i128, 1 << 20);
    assert!(
        r >= i64::MIN as i128 && r <= i64::MAX as i128,
        "relu2_q20: result exceeds i64"
    );
    r as i64
}

/// Integer silu(g)·up on the Q.20 grid.
///
/// `σ(g)` in Q0.31 via the exp LUT; both sign branches evaluate one exp of
/// `t = e^(−|g|)` so the argument is always non-negative:
///   g ≥ 0: `σ = rne(2^62 / (2^31 + t))`
///   g < 0: `σ = rne(t · 2^31 / (2^31 + t))`
/// (both are the same real function 1/(1+e^(−g)); at g = 0 both give
/// exactly 2^30 = 1/2, so the seam is continuous).
/// Then `silu = rne(g · σ / 2^31)` (Q.20) and `out = rne(silu · u / 2^20)`.
pub fn silu_q20(g: i64, u: i64, lut: &ExpLut) -> i64 {
    debug_assert!(
        g.unsigned_abs() < 1 << 40 && u.unsigned_abs() < 1 << 40,
        "silu_q20: inputs exceed the Q.20 headroom contract"
    );
    let sig_q31: i128 = if g >= 0 {
        let t = exp_neg_q31((g as u128) << 12, lut); // Q.20 → Q.32 arg
        rne_div(1i128 << 62, (1i128 << 31) + t as i128)
    } else {
        let t = exp_neg_q31((g.unsigned_abs() as u128) << 12, lut);
        rne_div((t as i128) << 31, (1i128 << 31) + t as i128)
    };
    let s = rne_div(g as i128 * sig_q31, 1 << 31); // Q.20
    let r = rne_div(s * u as i128, 1 << 20);
    assert!(
        r >= i64::MIN as i128 && r <= i64::MAX as i128,
        "silu_q20: result exceeds i64"
    );
    r as i64
}

// ---------------------------------------------------------------------------
// Unit goldens + properties. Constants computed by the INDEPENDENT big-int
// generator `scripts/cis_e2_golden_gen.py` (v0.3 sections) — never by the
// Rust under test.
// ---------------------------------------------------------------------------
#[cfg(test)]
mod tests {
    use super::*;
    use crate::cis_infer::{FNV1A64_OFFSET, fnv1a64};

    fn lcg_next(state: &mut u64) -> u64 {
        *state = state
            .wrapping_mul(6364136223846793005)
            .wrapping_add(1442695040888963407);
        *state
    }

    #[test]
    fn golden_exp2_chain() {
        let c = exp2_chain();
        assert_eq!(c[1], 3260954456333195553);
        assert_eq!(c[2], 3877950241171266237);
        assert_eq!(c[8], 4599216278082138664);
        assert_eq!(c[16], 4611637242788701949);
        assert_eq!(c[32], 4611686017683126785);
        let mut d = FNV1A64_OFFSET;
        for v in &c[1..=32] {
            d = fnv1a64(d, &v.to_le_bytes());
        }
        assert_eq!(d, 0x6CE6217F7A809D74);
    }

    #[test]
    fn golden_exp_lut() {
        let lut = ExpLut::new();
        assert_eq!(lut.entry(0), 1 << 31);
        assert_eq!(lut.entry(1), 2146030505);
        assert_eq!(lut.entry(512), 1518500250);
        assert_eq!(lut.entry(1023), 1074468888);
        assert_eq!(lut.entry(1024), 1 << 30);
        let mut d = FNV1A64_OFFSET;
        for i in 0..=1024 {
            d = fnv1a64(d, &(lut.entry(i) as u32).to_le_bytes());
        }
        assert_eq!(d, 0x66C2A0EEB8C2DC43);
        // Strictly decreasing entries: the monotone-lookup precondition.
        for i in 0..1024 {
            assert!(lut.entry(i) > lut.entry(i + 1), "LUT not decreasing at {i}");
        }
    }

    #[test]
    fn golden_log2_q32() {
        // log2(2.0) = 1 exactly; log2(4.0) = 2 exactly.
        assert_eq!(log2_q32_f32(2.0f32.to_bits()), 1 << 32);
        assert_eq!(log2_q32_f32(4.0f32.to_bits()), 2 << 32);
        // The two RoPE bases in scope (M7: 10000.0, BitNet-2B: 500000.0).
        assert_eq!(log2_q32_f32(10000.0f32.to_bits()), 57070290108);
        assert_eq!(log2_q32_f32(500000.0f32.to_bits()), 81310467867);
    }

    #[test]
    fn golden_exp_neg() {
        let lut = ExpLut::new();
        // (z_q32, expected Q0.31): e^0 = 2^31 exactly; z = ln 2 lands
        // exactly on 2^30; n >= 31 (z > ~21.49) underflows to exactly 0.
        assert_eq!(exp_neg_q31(0, &lut), 1 << 31);
        assert_eq!(exp_neg_q31(1 << 32, &lut), 790015124); // e^-1
        assert_eq!(exp_neg_q31(5 << 32, &lut), 14469632); // e^-5
        assert_eq!(exp_neg_q31(2977044472, &lut), 1073741824); // z = ln 2
        assert_eq!(exp_neg_q31(21 << 32, &lut), 2); // e^-21: near-last ulp
        assert_eq!(exp_neg_q31(22 << 32, &lut), 0); // n = 31: exact zero
        assert_eq!(exp_neg_q31(23 << 32, &lut), 0);
        assert_eq!(exp_neg_q31(1u128 << 80, &lut), 0);
    }

    #[test]
    fn exp_neg_monotone() {
        let lut = ExpLut::new();
        // Dense sweep around interpolation-segment and n-boundary seams.
        let mut prev = i64::MAX;
        let mut z: u128 = 0;
        let mut state = 0xA1CE_5EED_0000_0009u64;
        for _ in 0..50_000 {
            z += (lcg_next(&mut state) % (1 << 24)) as u128;
            let e = exp_neg_q31(z, &lut);
            assert!(e <= prev, "exp_neg not monotone at z = {z}");
            prev = e;
        }
    }

    #[test]
    fn golden_softmax_8() {
        const GOLDEN_P: [i32; 8] = [8860, 1178, 3948, 6664, 2926, 4387, 3224, 1579];
        let lut = ExpLut::new();
        let mut state = 0xA1CE_5EED_0000_0008u64;
        let mut s = [0i64; 8];
        for x in s.iter_mut() {
            // scores ~ ±2 real units on the Q.24 grid
            *x = ((lcg_next(&mut state) >> 30) % (1 << 26)) as i64 - (1 << 25);
        }
        let mut p = [0i32; 8];
        softmax_i(&mut s, &mut p, &lut);
        assert_eq!(p, GOLDEN_P);
        let sum: i64 = p.iter().map(|&x| x as i64).sum();
        assert!((sum - (1 << 15)).abs() <= 4, "sum {sum} outside ⌈T/2⌉");
    }

    #[test]
    fn softmax_uniform_and_sum_bound() {
        let lut = ExpLut::new();
        // All-equal scores: every e = 2^31, p = rne(2^15/T) exactly.
        let mut s = [7i64 << 24; 512];
        let mut p = [0i32; 512];
        softmax_i(&mut s, &mut p, &lut);
        assert!(p.iter().all(|&x| x == 64));
        assert_eq!(p.iter().map(|&x| x as i64).sum::<i64>(), 1 << 15);

        // Random vectors: |Σp − 2^15| ≤ ⌈T/2⌉ at several lengths.
        let mut state = 0xA1CE_5EED_0000_000Au64;
        for &n in &[2usize, 3, 17, 128, 512] {
            let mut s = alloc::vec![0i64; n];
            let mut p = alloc::vec![0i32; n];
            for x in s.iter_mut() {
                *x = ((lcg_next(&mut state) >> 28) % (1 << 28)) as i64 - (1 << 27);
            }
            let sref = s.clone();
            softmax_i(&mut s, &mut p, &lut);
            let sum: i64 = p.iter().map(|&x| x as i64).sum();
            assert!(
                (sum - (1 << 15)).unsigned_abs() <= n.div_ceil(2) as u64,
                "n={n}: sum {sum} outside the declared bound"
            );
            // Monotonicity: score order implies (non-strict) prob order.
            for i in 0..n {
                for j in 0..n {
                    if sref[i] >= sref[j] {
                        assert!(p[i] >= p[j], "monotonicity broken at ({i},{j})");
                    }
                }
            }
        }
    }

    #[test]
    fn golden_sincos() {
        // (x_q62, sin_q62, cos_q62) from the independent generator. Values
        // can exceed 2^62 by the Taylor truncation (~2e5 raw ulps at π/2,
        // i.e. ~4.4e-14); the Q1.30 requant clamp absorbs it.
        assert_eq!(sincos_q62(0), (0, 1 << 62));
        assert_eq!(sincos_q62(PI_2_Q62), (4611686018427588579, -2425842));
        assert_eq!(sincos_q62(PI_Q62), (0, -4611686018427387904));
        assert_eq!(sincos_q62(TWO_PI_Q62 - 1), (-1, 4611686018427387904));
        // 1.0 rad
        assert_eq!(
            sincos_q62(1 << 62),
            (3880599975550901295, 2491704589696178674)
        );
        // 2.5 rad
        assert_eq!(
            sincos_q62(5 << 61),
            (2759965619382477058, -3694622810570160725)
        );
    }

    #[test]
    fn golden_rope_table_m7() {
        // M7 shape: head_dim 64, seq 512, base 10000.0.
        let t = RopeTableI::new(512, 64, 10000.0f32.to_bits());
        // pos 0: identity rotation for every frequency.
        for d in 0..32 {
            assert_eq!((t.cos[d], t.sin[d]), (1 << 30, 0), "pos 0 d {d}");
        }
        // Spot goldens from the independent generator.
        assert_eq!((t.cos[32], t.sin[32]), (580145183, 903522590)); // pos 1, d 0
        assert_eq!((t.cos[63], t.sin[63]), (1073741814, 143186)); // pos 1, d 31
        assert_eq!(
            (t.cos[100 * 32 + 7], t.sin[100 * 32 + 7]),
            (771714489, 746577693)
        );
        assert_eq!(
            (t.cos[511 * 32 + 31], t.sin[511 * 32 + 31]),
            (1071249849, 73111318)
        );
        // Whole-table digest: cos then sin, LE i32, per (pos, d).
        let mut d = FNV1A64_OFFSET;
        for i in 0..512 * 32 {
            d = fnv1a64(d, &t.cos[i].to_le_bytes());
            d = fnv1a64(d, &t.sin[i].to_le_bytes());
        }
        assert_eq!(d, 0xD8345EBF01E990FA);
    }

    #[test]
    fn golden_rope_apply() {
        // One head, head_dim 4, pos 1, M7-shaped table (head_dim 4 → freqs
        // d=0 (θ=1 rad) and d=1 (θ=10^-2 rad)); goldens from the generator.
        let t = RopeTableI::new(4, 4, 10000.0f32.to_bits());
        let mut q = [1000000i32, -2000000, 3000000, 4000000];
        let mut k = [70000i32, 80000, -90000, 100000];
        rope_apply_i(&mut q, &mut k, 1, 1, 1, 4, &t);
        assert_eq!(q, [-1984111, -2039899, 2462378, 3979800]);
        assert_eq!(k, [113554, 78996, 10276, 100795]);
    }

    #[test]
    fn rope_norm_preservation() {
        let t = RopeTableI::new(512, 64, 10000.0f32.to_bits());
        let mut state = 0xA1CE_5EED_0000_000Bu64;
        for &pos in &[1usize, 17, 255, 511] {
            let mut q = [0i32; 64];
            let mut k = [0i32; 64];
            for x in q.iter_mut().chain(k.iter_mut()) {
                *x = ((lcg_next(&mut state) >> 33) % (1 << 21)) as i32 - (1 << 20);
            }
            let s2_before: i128 = q.iter().map(|&v| v as i128 * v as i128).sum();
            let mut kk = [0i32; 64];
            rope_apply_i(&mut q, &mut kk, pos, 1, 0, 64, &t);
            let s2_after: i128 = q.iter().map(|&v| v as i128 * v as i128).sum();
            // Rotation preserves the norm; table + requant error is bounded
            // well below 2^-13 relative for |q| up to 2^21.
            let diff = (s2_after - s2_before).unsigned_abs();
            assert!(
                diff <= (s2_before as u128 >> 13).max(1 << 12),
                "pos {pos}: norm drifted by {diff} of {s2_before}"
            );
        }
    }

    #[test]
    fn golden_inv_sqrt() {
        assert_eq!(inv_sqrt_q30(1), 1 << 30);
        assert_eq!(inv_sqrt_q30(4), 1 << 29);
        assert_eq!(inv_sqrt_q30(64), 1 << 27); // M7 head_dim: exact
        assert_eq!(inv_sqrt_q30(128), 94906266); // BitNet-2B head_dim
    }

    #[test]
    fn golden_relu2() {
        // (g, u, expected) on Q.20 — from the independent generator.
        assert_eq!(relu2_q20(-5 << 20, 3 << 20), 0);
        assert_eq!(relu2_q20(0, 3 << 20), 0);
        assert_eq!(relu2_q20(1 << 20, 1 << 20), 1 << 20);
        assert_eq!(relu2_q20(3 << 19, 1 << 21), 4718592); // 1.5² · 2 = 4.5
        assert_eq!(relu2_q20(7, 1 << 20), 0); // tiny g: g²/2^20 rounds to 0
        assert_eq!(relu2_q20(724, 1 << 20), 0); // g²/2^20 = 0.49994 → rne 0
    }

    #[test]
    fn golden_silu() {
        let lut = ExpLut::new();
        // (g, u, expected) on Q.20 — from the independent generator.
        assert_eq!(silu_q20(0, 5 << 20, &lut), 0);
        assert_eq!(silu_q20(1 << 20, 1 << 20, &lut), 766570); // silu(1) ≈ 0.7311
        assert_eq!(silu_q20(-(1i64 << 20), 1 << 20, &lut), -282006); // silu(−1)
        assert_eq!(silu_q20(10 << 20, 1 << 20, &lut), 10485284); // ≈ 10
        assert_eq!(silu_q20(-(10i64 << 20), 1 << 20, &lut), -476); // ≈ −4.5e−4
        assert_eq!(silu_q20(-(30i64 << 20), 1 << 20, &lut), 0); // exp underflow
        assert_eq!(silu_q20(3 << 19, -(1i64 << 20), &lut), -1285933);
    }

    /// σ seam: both sign branches at g = ±1 (smallest Q.20 ulp) bracket the
    /// g = 0 value monotonically; the RNE ties at |σ·g| ≈ 0.5 ulp resolve
    /// to at most one output ulp (goldens from the generator).
    #[test]
    fn silu_sign_seam() {
        let lut = ExpLut::new();
        let a = silu_q20(-1, 1 << 20, &lut);
        let b = silu_q20(0, 1 << 20, &lut);
        let c = silu_q20(1, 1 << 20, &lut);
        assert_eq!((a, b, c), (0, 0, 1));
        assert!(a <= b && b <= c, "silu seam not monotone: {a} {b} {c}");
    }
}
